doc: add minutes for meeting 2021-06-17
nodejs/Release pull request #680
Opened 2021-06-25 10:51 UTC by BethGriggs

Fixes: https://github.com/nodejs/Release/issues/678

_Belated 😇_

2021-06-25 11:24 UTC, richardlau approved these changes

2021-06-25 12:04 UTC, bl-ue requested changes

2021-06-25 12:04 UTC, bl-ue commented on doc/meetings/2021-06-17.md
> +  * Changed the minimum ICU version in an LTS line (14.x) and that has broken building against the system ICU.
```suggestion
  * Changed the minimum ICU version in an LTS line (14.x) and that has broken building against the system ICU.
```

2021-06-28 20:24 UTC, mhdawson approved these changes
LGTM

2021-06-29 06:38 UTC, targos approved these changes

2021-06-29 09:30 UTC, merged