doc: clarify and update releaser onboarding steps
nodejs/Release pull request #731
Opened 2022-02-26 17:08 UTC by bengl

Having just gone through this process, some clarification was warranted, and two new ones were added:

* Adding gpg key to `nodejs/release-keys`
* Adding themself in this repo's README

2022-02-27 10:30 UTC, targos approved these changes

2022-02-27 21:22 UTC, cjihrig approved these changes

2022-02-27 22:55 UTC, richardlau approved these changes

2022-03-02 03:56 UTC, danielleadams requested changes

2022-03-02 03:56 UTC, danielleadams commented on GOVERNANCE.md
> +* Open a PR to add their GPG key to the nodejs/node [README.md](https://github.com/nodejs/node/#release-team)
What anchor is the README link supposed to link to? I don't think that anchor exists anymore. Maybe it needs to be https://github.com/nodejs/node/#release-keys?
```suggestion
* Open a PR to add their GPG key to the nodejs/node [README.md](https://github.com/nodejs/node/#release-keys)
```

2022-03-02 16:02 UTC, danielleadams approved these changes

2022-03-02 16:16 UTC, richardlau approved these changes

2022-03-02 19:56 UTC, BethGriggs approved these changes

2022-03-07 16:21 UTC, merged